#!/usr/bin/env bash

set -e

create_superuser="
import django
django.setup()
from django.contrib.auth.models import User
try:
    User.objects.create_superuser('$DJANGO_SUPERUSER_NAME', '$DJANGO_SUPERUSER_MAIL', '$DJANGO_SUPERUSER_PASS')
except Exception:
    pass
"

create_superuser() {
    if [[ ! -v $DJANGO_SUPERUSER_NAME ]] || [[ ! -v $DJANGO_SUPERUSER_MAIL ]] || [[ ! -v $DJANGO_SUPERUSER_PASS ]]; then
        echo "Environment variables for django superuser not set, not creating superuser."
    else
        echo "Creating superuser"
        python -c "$create_superuser"
    fi
}

wait_for_db() {
    if [[ ! -v $DJANGO_DB_HOST ]] || [[ ! -v $DJANGO_DB_PORT ]]; then
        echo "Environment variables for django database host or port not set, not waiting for db."
    else
        echo "Waiting for database"
        dockerize -wait tcp://"$DJANGO_DB_HOST":"$DJANGO_DB_PORT" -timeout 30s
    fi
}

if [ "$1" == "runserver" ]; then
    wait_for_db

    echo "Running migrations"
    # Apply database migrations
    python manage.py migrate
    # Collect static files
    echo "Running collectstatic"
    python manage.py collectstatic --noinput

    create_superuser

    exec python manage.py "$@"
fi

if [ "$1" == "nomigrate" ]; then
    wait_for_db

    echo "Running collectstatic"
    python manage.py collectstatic --noinput

    create_superuser

    exec python manage.py runserver "${@:2}"
fi

if [ "$1" == "migrate" ]; then
    wait_for_db

    echo "Running migrations"
    # Apply database migrations
    python manage.py "$@"
fi

if [ "$1" == "makemigrations" ];then
    wait_for_db
    exec python manage.py "$@"
fi

if [ "$1" == "loadtestdata" ];then
    wait_for_db
    exec python manage.py "$@"
fi

exec "$@"
